name = "dotenv"
description = "Loads environment variables from .env for Ada projects."
version = "1.1.0"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = ["BSD 2-Clauses"]

website = "https://github.com/Heziode/ada-dotenv"
tags = [
    "dotenv",
    "env",
    ".env",
    "environment",
    "variables",
    "config",
    "settings"
]
